"""initial migration

Revision ID: 6ef4cb4ba8fc
Revises: 
Create Date: 2025-05-22 20:27:54.157175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef4cb4ba8fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_signature', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_signature'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['from_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'job_title', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('from_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('signature')
        batch_op.drop_column('user_signature')
        batch_op.drop_column('is_signature')

    # ### end Alembic commands ###
