"""add digital signature fields to documents

Revision ID: 986a684359bf
Revises: 
Create Date: 2025-05-20 22:19:44.760678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '986a684359bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_signature', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))
        batch_op.alter_column('transfer_number',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('sender_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('recipient_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key(None, 'users', ['user_signature'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['verify_user'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'documents', ['doc_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('from_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key(None, 'users', ['from_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('from_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('recipient_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sender_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('transfer_number',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('signature')
        batch_op.drop_column('user_signature')
        batch_op.drop_column('is_signature')

    # ### end Alembic commands ###
