"""initial migration

Revision ID: df4659d630b7
Revises: 
Create Date: 2025-05-28 23:01:39.082025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df4659d630b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['verify_user'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'documents', ['doc_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('from_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key(None, 'users', ['from_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key(None, 'branchs', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('from_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
